name: git demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  describe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: coolestowl/gh-action-demo
      - run: |
          git fetch --unshallow --tags
          echo $?

          git describe --tags
      - run: |
          pwd
          tree

