name: Golang CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: go test
      run: go test -v ./...

    - name: static build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o main cmd/*.go
